title: "My Portfolio"
description: "Welcome to my portfolio website."
baseurl: ""  # Leave empty if deploying to GitHub Pages without a subdirectory
url: "https://your-github-username.github.io"  # Replace with your GitHub Pages URL

# Theme (GitHub Pages supports minimal-mistakes, jekyll-theme-minimal, etc.)
theme: jekyll-theme-minimal

# Author Info
author:
  name: "Your Name"
  email: "your.email@example.com"

# Navigation (if using a theme that supports it)
nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "About"
    url: "/about"

# Plugins (GitHub Pages allows these by default)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude these files from the build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
